Class {
	#name : 'PjClassBForCircularTranspilationTest',
	#superclass : 'PjClassAForCircularTranspilationTest',
	#category : 'PharoJs-Base-Transpiler-Tests-Support',
	#package : 'PharoJs-Base-Transpiler-Tests',
	#tag : 'Support'
}

{ #category : 'any' }
PjClassBForCircularTranspilationTest class >> javascriptName [
	^super javascriptName
]

{ #category : 'any' }
PjClassBForCircularTranspilationTest class >> other [
	^ Object isNil
]
