# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "pharo10", "coverall" ]
  pull_request:
    branches: [ "pharo10" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Pharo64-10'
      - uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - name: Cache apt-install
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: xdg-utils 
      - run: xdg-settings set default-web-browser firefox.desktop 
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g npm@latest
      - name: setup-xvfb
        uses: coactions/setup-xvfb@v1.0.1
        with:
          # Command to execute using xvfb
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ubuntu-pharo10
          parallel: true
          run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true